name: detect-new-jobs in /src/sparkjobs/
on:
  push:
    paths:
      - 'src/sparkjobs/**'

jobs:
  detect-new-jobs:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List new files
        run: |
          kubectl exec -it spark-driver-ss-0 -- ./submit-jobs.sh